package testpair

import (
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

// ///////////////////////////////////////////////
// Helpers
// ///////////////////////////////////////////////

// writeFile writes content to a path under dir, creating parents as needed.
func writeFile(t *testing.T, dir, rel, content string) {
	t.Helper()
	full := filepath.Join(dir, rel)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", rel, err)
	}
}

// ///////////////////////////////////////////////
// compareIssue
// ///////////////////////////////////////////////

func TestCompareIssue_ByKindThenFileThenMessage(t *testing.T) {
	issues := []Issue{
		{Kind: "missing-test", File: "b.go", Message: "z"},
		{Kind: "missing-test", File: "a.go", Message: "y"},
		{Kind: "orphan-test", File: "z.go", Message: "a"},
		{Kind: "missing-test", File: "a.go", Message: "x"},
	}
	slices.SortFunc(issues, compareIssue)
	want := []Issue{
		{Kind: "missing-test", File: "a.go", Message: "x"},
		{Kind: "missing-test", File: "a.go", Message: "y"},
		{Kind: "missing-test", File: "b.go", Message: "z"},
		{Kind: "orphan-test", File: "z.go", Message: "a"},
	}
	for i, got := range issues {
		if got != want[i] {
			t.Errorf("sorted[%d] = %+v, want %+v", i, got, want[i])
		}
	}
}

// ///////////////////////////////////////////////
// extractTestBase
// ///////////////////////////////////////////////

func TestExtractTestBase(t *testing.T) {
	tests := []struct {
		name, want string
	}{
		{"TestFoo", "Foo"},
		{"TestFoo_Bar", "Foo"},
		{"TestFoo_Bar_Baz", "Foo"},
		{"Test", ""},
		{"TestParseArgs_JSONFlag", "ParseArgs"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := extractTestBase(tt.name); got != tt.want {
				t.Errorf("extractTestBase(%q) = %q, want %q", tt.name, got, tt.want)
			}
		})
	}
}

// ///////////////////////////////////////////////
// upperFirst
// ///////////////////////////////////////////////

func TestUpperFirst(t *testing.T) {
	tests := map[string]string{
		"":     "",
		"a":    "A",
		"foo":  "Foo",
		"fooX": "FooX",
		"X":    "X",
	}
	for in, want := range tests {
		if got := upperFirst(in); got != want {
			t.Errorf("upperFirst(%q) = %q, want %q", in, got, want)
		}
	}
}

// ///////////////////////////////////////////////
// isGenerated
// ///////////////////////////////////////////////

func TestIsGenerated(t *testing.T) {
	dir := t.TempDir()
	tests := []struct {
		name, content string
		want          bool
	}{
		{"autogen.go", "// Auto-generated by foo. Do not edit.\npackage x\n", true},
		{"codegen.go", "// Code generated by bar; DO NOT EDIT.\npackage x\n", true},
		{"donotedit.go", "// DO NOT EDIT — built from y\npackage x\n", true},
		{"regular.go", "// Package x does things.\npackage x\n", false},
		{"missing.go", "", false}, // never created
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			path := filepath.Join(dir, tt.name)
			if tt.content != "" {
				if err := os.WriteFile(path, []byte(tt.content), 0o644); err != nil {
					t.Fatalf("write: %v", err)
				}
			}
			if got := isGenerated(path); got != tt.want {
				t.Errorf("isGenerated(%q) = %v, want %v", tt.name, got, tt.want)
			}
		})
	}
}

// ///////////////////////////////////////////////
// Check functions against fixture dirs
// ///////////////////////////////////////////////

func TestFindMissingTests_FlagsUnpairedSource(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "foo/bar.go", "package foo\nfunc Bar() {}\n")
	writeFile(t, dir, "foo/baz.go", "package foo\nfunc Baz() {}\n")
	writeFile(t, dir, "foo/baz_test.go", "package foo\nfunc TestBaz(t *testing.T) {}\n")

	sources := map[string][]string{
		filepath.Join(dir, "foo"): {"bar.go", "baz.go"},
	}
	tests := map[string][]string{
		filepath.Join(dir, "foo"): {"baz_test.go"},
	}

	issues := findMissingTests(sources, tests)
	if len(issues) != 1 {
		t.Fatalf("expected 1 missing-test issue, got %d: %v", len(issues), issues)
	}
	if !strings.HasSuffix(issues[0].File, "bar.go") {
		t.Errorf("expected issue on bar.go, got %+v", issues[0])
	}
}

func TestFindMissingTests_SkipsGenerated(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "foo/generated.go", "// Code generated — DO NOT EDIT.\npackage foo\n")

	sources := map[string][]string{filepath.Join(dir, "foo"): {"generated.go"}}
	tests := map[string][]string{}

	issues := findMissingTests(sources, tests)
	if len(issues) != 0 {
		t.Errorf("generated files should be skipped; got %v", issues)
	}
}

func TestFindOrphanTests_FlagsTestWithoutSource(t *testing.T) {
	sources := map[string][]string{"foo": {"bar.go"}}
	tests := map[string][]string{"foo": {"bar_test.go", "baz_test.go"}}

	issues := findOrphanTests(sources, tests)
	if len(issues) != 1 {
		t.Fatalf("expected 1 orphan-test issue, got %d: %v", len(issues), issues)
	}
	if !strings.Contains(issues[0].File, "baz_test.go") {
		t.Errorf("expected issue on baz_test.go, got %+v", issues[0])
	}
}

func TestFindNamingMismatches_FlagsUnknownSymbol(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "foo/bar.go", "package foo\n\nfunc Bar() {}\n")
	writeFile(t, dir, "foo/bar_test.go", `package foo

import "testing"

func TestBar(t *testing.T) {}
func TestGhost(t *testing.T) {}
`)

	pkgDir := filepath.Join(dir, "foo")
	sources := map[string][]string{pkgDir: {"bar.go"}}
	tests := map[string][]string{pkgDir: {"bar_test.go"}}

	issues := findNamingMismatches(sources, tests)
	if len(issues) != 1 {
		t.Fatalf("expected 1 name-mismatch, got %d: %v", len(issues), issues)
	}
	if !strings.Contains(issues[0].Message, "Ghost") {
		t.Errorf("expected message mentioning Ghost, got %+v", issues[0])
	}
}
