package testpair

import (
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"zach.tools/go/devtools/internal/scope"
)

// ///////////////////////////////////////////////
// Helpers
// ///////////////////////////////////////////////

// writeFile writes content to a path under dir, creating parents as needed.
func writeFile(t *testing.T, dir, rel, content string) {
	t.Helper()
	full := filepath.Join(dir, rel)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", rel, err)
	}
}

// ///////////////////////////////////////////////
// compareIssue
// ///////////////////////////////////////////////

func TestCompareIssue_ByKindThenFileThenMessage(t *testing.T) {
	issues := []Issue{
		{Kind: "missing-test", File: "b.go", Message: "z"},
		{Kind: "missing-test", File: "a.go", Message: "y"},
		{Kind: "orphan-test", File: "z.go", Message: "a"},
		{Kind: "missing-test", File: "a.go", Message: "x"},
	}
	slices.SortFunc(issues, compareIssue)
	want := []Issue{
		{Kind: "missing-test", File: "a.go", Message: "x"},
		{Kind: "missing-test", File: "a.go", Message: "y"},
		{Kind: "missing-test", File: "b.go", Message: "z"},
		{Kind: "orphan-test", File: "z.go", Message: "a"},
	}
	for i, got := range issues {
		if got != want[i] {
			t.Errorf("sorted[%d] = %+v, want %+v", i, got, want[i])
		}
	}
}

// ///////////////////////////////////////////////
// extractTestBase
// ///////////////////////////////////////////////

func TestExtractTestBase(t *testing.T) {
	tests := []struct {
		name, want string
	}{
		{"TestFoo", "Foo"},
		{"TestFoo_Bar", "Foo"},
		{"TestFoo_Bar_Baz", "Foo"},
		{"Test", ""},
		{"TestParseArgs_JSONFlag", "ParseArgs"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := extractTestBase(tt.name); got != tt.want {
				t.Errorf("extractTestBase(%q) = %q, want %q", tt.name, got, tt.want)
			}
		})
	}
}

// ///////////////////////////////////////////////
// upperFirst
// ///////////////////////////////////////////////

func TestUpperFirst(t *testing.T) {
	tests := map[string]string{
		"":     "",
		"a":    "A",
		"foo":  "Foo",
		"fooX": "FooX",
		"X":    "X",
	}
	for in, want := range tests {
		if got := upperFirst(in); got != want {
			t.Errorf("upperFirst(%q) = %q, want %q", in, got, want)
		}
	}
}

// ///////////////////////////////////////////////
// isGenerated
// ///////////////////////////////////////////////

func TestIsGenerated(t *testing.T) {
	dir := t.TempDir()
	tests := []struct {
		name, content string
		want          bool
	}{
		{"autogen.go", "// Auto-generated by foo. Do not edit.\npackage x\n", true},
		{"codegen.go", "// Code generated by bar; DO NOT EDIT.\npackage x\n", true},
		{"donotedit.go", "// DO NOT EDIT — built from y\npackage x\n", true},
		{"regular.go", "// Package x does things.\npackage x\n", false},
		{"missing.go", "", false}, // never created
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			path := filepath.Join(dir, tt.name)
			if tt.content != "" {
				if err := os.WriteFile(path, []byte(tt.content), 0o644); err != nil {
					t.Fatalf("write: %v", err)
				}
			}
			if got := isGenerated(path); got != tt.want {
				t.Errorf("isGenerated(%q) = %v, want %v", tt.name, got, tt.want)
			}
		})
	}
}

// ///////////////////////////////////////////////
// Check functions against fixture dirs
// ///////////////////////////////////////////////

func TestFindMissingTests_FlagsUnpairedSource(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "foo/bar.go", "package foo\nfunc Bar() {}\n")
	writeFile(t, dir, "foo/baz.go", "package foo\nfunc Baz() {}\n")
	writeFile(t, dir, "foo/baz_test.go", "package foo\nfunc TestBaz(t *testing.T) {}\n")

	sources := map[string][]string{
		filepath.Join(dir, "foo"): {"bar.go", "baz.go"},
	}
	tests := map[string][]string{
		filepath.Join(dir, "foo"): {"baz_test.go"},
	}

	issues := findMissingTests(sources, tests)
	if len(issues) != 1 {
		t.Fatalf("expected 1 missing-test issue, got %d: %v", len(issues), issues)
	}
	if !strings.HasSuffix(issues[0].File, "bar.go") {
		t.Errorf("expected issue on bar.go, got %+v", issues[0])
	}
}

func TestFindMissingTests_SkipsGenerated(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "foo/generated.go", "// Code generated — DO NOT EDIT.\npackage foo\n")

	sources := map[string][]string{filepath.Join(dir, "foo"): {"generated.go"}}
	tests := map[string][]string{}

	issues := findMissingTests(sources, tests)
	if len(issues) != 0 {
		t.Errorf("generated files should be skipped; got %v", issues)
	}
}

func TestFindOrphanTests_FlagsTestWithoutSource(t *testing.T) {
	sources := map[string][]string{"foo": {"bar.go"}}
	tests := map[string][]string{"foo": {"bar_test.go", "baz_test.go"}}

	issues := findOrphanTests(sources, tests)
	if len(issues) != 1 {
		t.Fatalf("expected 1 orphan-test issue, got %d: %v", len(issues), issues)
	}
	if !strings.Contains(issues[0].File, "baz_test.go") {
		t.Errorf("expected issue on baz_test.go, got %+v", issues[0])
	}
}

func TestFindNamingMismatches_FlagsUnknownSymbol(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "foo/bar.go", "package foo\n\nfunc Bar() {}\n")
	writeFile(t, dir, "foo/bar_test.go", `package foo

import "testing"

func TestBar(t *testing.T) {}
func TestGhost(t *testing.T) {}
`)

	pkgDir := filepath.Join(dir, "foo")
	sources := map[string][]string{pkgDir: {"bar.go"}}
	tests := map[string][]string{pkgDir: {"bar_test.go"}}

	issues, errs := findNamingMismatches(sources, tests)
	if len(errs) != 0 {
		t.Fatalf("unexpected parse errors: %v", errs)
	}
	if len(issues) != 1 {
		t.Fatalf("expected 1 name-mismatch, got %d: %v", len(issues), issues)
	}
	if !strings.Contains(issues[0].Message, "Ghost") {
		t.Errorf("expected message mentioning Ghost, got %+v", issues[0])
	}
}

func TestFindNamingMismatches_ReportsASourceFileItCannotParse(t *testing.T) {
	// A symbol set built from a partial read is missing whatever the
	// unreadable file declared, so tests naming those symbols look like
	// mismatches. Surfacing the parse failure is what stops the tool
	// reporting its own blindness as a finding about the code.
	dir := t.TempDir()
	writeFile(t, dir, "foo/bar.go", "package foo\n\nfunc Bar() {}\n")
	writeFile(t, dir, "foo/broken.go", "package foo\n\nfunc Ghost( {}\n")
	writeFile(t, dir, "foo/bar_test.go", `package foo

import "testing"

func TestGhost(t *testing.T) {}
`)

	pkgDir := filepath.Join(dir, "foo")
	sources := map[string][]string{pkgDir: {"bar.go", "broken.go"}}
	tests := map[string][]string{pkgDir: {"bar_test.go"}}

	_, errs := findNamingMismatches(sources, tests)

	if len(errs) != 1 {
		t.Fatalf("expected 1 parse error, got %d: %v", len(errs), errs)
	}
	if !strings.Contains(errs[0].Error(), "broken.go") {
		t.Errorf("parse error does not name the file: %v", errs[0])
	}
}

func TestFindNamingMismatches_ReportsATestFileItCannotParse(t *testing.T) {
	// A test file that fails to parse contributes no test functions, so
	// every convention violation inside it goes unreported.
	dir := t.TempDir()
	writeFile(t, dir, "foo/bar.go", "package foo\n\nfunc Bar() {}\n")
	writeFile(t, dir, "foo/bar_test.go", "package foo\n\nfunc TestGhost( {}\n")

	pkgDir := filepath.Join(dir, "foo")
	sources := map[string][]string{pkgDir: {"bar.go"}}
	tests := map[string][]string{pkgDir: {"bar_test.go"}}

	issues, errs := findNamingMismatches(sources, tests)

	if len(errs) != 1 {
		t.Fatalf("expected 1 parse error, got %d: %v", len(errs), errs)
	}
	if !strings.Contains(errs[0].Error(), "bar_test.go") {
		t.Errorf("parse error does not name the file: %v", errs[0])
	}
	if len(issues) != 0 {
		t.Errorf("a file that did not parse produced findings: %v", issues)
	}
}

func TestFindNamingMismatches_AcceptsTheTestBinaryEntryPoint(t *testing.T) {
	// TestMain(m *testing.M) is named for the role go test gives it, not for
	// a symbol under test. Flagging it asks every package that defines one
	// to declare a symbol called Main, which no package has.
	dir := t.TempDir()
	writeFile(t, dir, "foo/bar.go", "package foo\n\nfunc Bar() {}\n")
	writeFile(t, dir, "foo/bar_test.go", `package foo

import (
	"os"
	"testing"
)

func TestMain(m *testing.M) { os.Exit(m.Run()) }
func TestBar(t *testing.T)  {}
`)

	pkgDir := filepath.Join(dir, "foo")
	sources := map[string][]string{pkgDir: {"bar.go"}}
	tests := map[string][]string{pkgDir: {"bar_test.go"}}

	issues, errs := findNamingMismatches(sources, tests)

	if len(errs) != 0 {
		t.Fatalf("unexpected parse errors: %v", errs)
	}
	if len(issues) != 0 {
		t.Errorf("the test binary entry point was flagged: %v", issues)
	}
}

func TestFindNamingMismatches_StillChecksATestNamedForASymbolCalledMain(t *testing.T) {
	// The exemption is for the entry point, which go test identifies by its
	// parameter. A TestMain taking *testing.T is an ordinary test, so the
	// symbol rule still applies and there is no symbol Main to satisfy it.
	dir := t.TempDir()
	writeFile(t, dir, "foo/bar.go", "package foo\n\nfunc Bar() {}\n")
	writeFile(t, dir, "foo/bar_test.go", `package foo

import "testing"

func TestMain(t *testing.T) {}
`)

	pkgDir := filepath.Join(dir, "foo")
	sources := map[string][]string{pkgDir: {"bar.go"}}
	tests := map[string][]string{pkgDir: {"bar_test.go"}}

	issues, _ := findNamingMismatches(sources, tests)

	if len(issues) != 1 {
		t.Fatalf("expected 1 name-mismatch, got %d: %v", len(issues), issues)
	}
	if !strings.Contains(issues[0].Message, "Main") {
		t.Errorf("expected a message about the symbol Main, got %+v", issues[0])
	}
}

func TestFindNamingMismatches_ReportsATestThatNamesNoSymbol(t *testing.T) {
	// `func Test(t *testing.T)` is a legal test that go test runs, and it
	// names nothing for the convention to check. Passing over it silently
	// exempts it without an allow entry, so one test per package could
	// always sidestep the rule.
	dir := t.TempDir()
	writeFile(t, dir, "foo/bar.go", "package foo\n\nfunc Bar() {}\n")
	writeFile(t, dir, "foo/bar_test.go", `package foo

import "testing"

func Test(t *testing.T) {}
`)

	pkgDir := filepath.Join(dir, "foo")
	sources := map[string][]string{pkgDir: {"bar.go"}}
	tests := map[string][]string{pkgDir: {"bar_test.go"}}

	issues, _ := findNamingMismatches(sources, tests)

	if len(issues) != 1 {
		t.Fatalf("expected 1 finding for a test naming no symbol, got %d: %v", len(issues), issues)
	}
	if !strings.Contains(issues[0].Message, "names no symbol") {
		t.Errorf("message does not say what is wrong: %+v", issues[0])
	}
}

func TestFindNamingMismatches_ChecksAPackageWhoseSourceDeclaresNothing(t *testing.T) {
	// An empty symbol set means every test name in the package matches
	// nothing, which is the strongest form of the finding rather than a
	// reason to skip. Skipping let a doc.go with a package clause carry any
	// test name at all.
	dir := t.TempDir()
	writeFile(t, dir, "foo/doc.go", "// Package foo does nothing.\npackage foo\n")
	writeFile(t, dir, "foo/doc_test.go", `package foo

import "testing"

func TestCompletelyMadeUp(t *testing.T) {}
`)

	pkgDir := filepath.Join(dir, "foo")
	sources := map[string][]string{pkgDir: {"doc.go"}}
	tests := map[string][]string{pkgDir: {"doc_test.go"}}

	issues, errs := findNamingMismatches(sources, tests)

	if len(errs) != 0 {
		t.Fatalf("unexpected parse errors: %v", errs)
	}
	if len(issues) != 1 {
		t.Fatalf("expected 1 name-mismatch, got %d: %v", len(issues), issues)
	}
	if !strings.Contains(issues[0].Message, "CompletelyMadeUp") {
		t.Errorf("message does not name the test: %+v", issues[0])
	}
}

func TestFindNamingMismatches_SkipsADirectoryWithNoSourceAtAll(t *testing.T) {
	// The orphan-test check already answers for a directory holding only
	// tests, and its test names have nothing to be matched against. A
	// second finding on the same file would say the same thing twice.
	dir := t.TempDir()
	writeFile(t, dir, "foo/orphan_test.go", `package foo

import "testing"

func TestGhost(t *testing.T) {}
`)

	pkgDir := filepath.Join(dir, "foo")
	sources := map[string][]string{}
	tests := map[string][]string{pkgDir: {"orphan_test.go"}}

	issues, _ := findNamingMismatches(sources, tests)

	if len(issues) != 0 {
		t.Errorf("a source-free directory produced name-mismatch findings: %v", issues)
	}
}

// ///////////////////////////////////////////////
// collectFiles
// ///////////////////////////////////////////////

func TestCollectFiles_SplitsSourceFromTest(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "bar.go", "package foo\n")
	writeFile(t, dir, "bar_test.go", "package foo\n")
	writeFile(t, dir, "notes.txt", "ignored\n")

	sources := map[string][]string{}
	tests := map[string][]string{}
	if err := collectFiles(dir, sources, tests); err != nil {
		t.Fatalf("collectFiles: %v", err)
	}

	if !slices.Equal(sources[dir], []string{"bar.go"}) {
		t.Errorf("sources = %v, want [bar.go]", sources[dir])
	}
	if !slices.Equal(tests[dir], []string{"bar_test.go"}) {
		t.Errorf("tests = %v, want [bar_test.go]", tests[dir])
	}
}

func TestCollectFiles_ReportsADirectoryItCannotRead(t *testing.T) {
	// An unreadable directory contributes no files, so every convention
	// its package violates goes unreported. Answering with an error is
	// what keeps that from reading as a package with nothing wrong.
	missing := filepath.Join(t.TempDir(), "does-not-exist")

	err := collectFiles(missing, map[string][]string{}, map[string][]string{})

	if err == nil {
		t.Fatal("collectFiles accepted a directory it could not read")
	}
	if !strings.Contains(err.Error(), "does-not-exist") {
		t.Errorf("error does not name the directory: %v", err)
	}
}

// ///////////////////////////////////////////////
// allowPath
// ///////////////////////////////////////////////

func TestAllowPath_ResolvesAnIssueToAPathScopeMatchingAccepts(t *testing.T) {
	// The round trip the accessor exists for. An issue's own canonical line
	// has to resolve to a path a scope matcher accepts, or every entry
	// filters out of scope and the tool rejects the allow file it wrote.
	issue := Issue{
		Kind:    "missing-test",
		File:    "internal/foo/bar.go",
		Message: "expected internal/foo/bar_test.go",
	}

	if got, want := allowPath(issue.String()), "internal/foo/bar.go"; got != want {
		t.Errorf("allowPath(%q) = %q, want %q", issue.String(), got, want)
	}
	if !scope.Matcher([]string{"internal/foo"})(allowPath(issue.String())) {
		t.Error("a scoped run drops an entry that is inside its own scope")
	}
}

func TestAllowPath_AnswersWithWhatALineTooShortToSplitHolds(t *testing.T) {
	// A hand-edited allow file is ordinary. A line with no second field has
	// no path to give, and answering empty would match every scope.
	if got, want := allowPath("missing-test"), "missing-test"; got != want {
		t.Errorf("allowPath = %q, want %q", got, want)
	}
}
